// <auto-generated />
using System;
using HrDraft.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrDraft.DAL.Migrations
{
    [DbContext(typeof(HrDraftDbContext))]
    partial class HrDraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HrDraft.Model.Entities.AppSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingKey");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            SettingKey = "DefaultDailyGenerationLimit",
                            Description = "Runs per person per day when the user row does not override it.",
                            SettingValue = "20",
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SettingKey = "ClaudeModelId",
                            Description = "Model used for every generation. Changing it needs no deploy.",
                            SettingValue = "claude-sonnet-5",
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SettingKey = "GenerationHistoryRetentionDays",
                            Description = "Age at which a draft's text is nulled. The row and its audit entries stay.",
                            SettingValue = "730",
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HrDraft.Model.Entities.AuditEntry", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("CreatedUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLog_CreatedUtc");

                    b.HasIndex("UserId", "CreatedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLog_UserId_CreatedUtc");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.CompBand", b =>
                {
                    b.Property<int>("CompBandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompBandId"));

                    b.Property<decimal?>("BonusPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DisplayOverride")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LevelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CompBandId");

                    b.HasIndex("CompanyProfileId", "SortOrder");

                    b.ToTable("CompBands", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.CompanyProfile", b =>
                {
                    b.Property<int>("CompanyProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyProfileId"));

                    b.Property<string>("BenefitsBlurb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CultureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeiStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyProfileId");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyProfiles_IsCurrent")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CompanyProfiles", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.EmailMessage", b =>
                {
                    b.Property<long>("EmailMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmailMessageId"));

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("GenerationId")
                        .HasColumnType("bigint");

                    b.Property<string>("GraphMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SentByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailMessageId");

                    b.HasIndex("CreatedUtc")
                        .IsDescending();

                    b.HasIndex("GenerationId");

                    b.HasIndex("SentByUserId");

                    b.ToTable("EmailMessages", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.Generation", b =>
                {
                    b.Property<long>("GenerationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenerationId"));

                    b.Property<int?>("CacheReadInputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("EditedMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("ModelId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OutputMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<long?>("ParentGenerationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GenerationId");

                    b.HasIndex("CompanyProfileId");

                    b.HasIndex("ParentGenerationId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("ToolId", "CreatedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Generations_ToolId_CreatedUtc");

                    b.HasIndex("UserId", "CreatedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Generations_UserId_CreatedUtc");

                    b.ToTable("Generations", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.GenerationRevision", b =>
                {
                    b.Property<long>("GenerationRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenerationRevisionId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("GenerationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsModelOutput")
                        .HasColumnType("bit");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("GenerationRevisionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GenerationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("GenerationRevisions", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.LookupOption", b =>
                {
                    b.Property<int>("LookupOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LookupOptionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GroupLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShortLabel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("LookupOptionId");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("LookupOptions", (string)null);

                    b.HasData(
                        new
                        {
                            LookupOptionId = 1,
                            Category = "WorkArrangement",
                            GroupLabel = "Arrangement",
                            IsEnabled = true,
                            Label = "On-site",
                            SortOrder = 1,
                            Value = "onsite"
                        },
                        new
                        {
                            LookupOptionId = 2,
                            Category = "WorkArrangement",
                            GroupLabel = "Arrangement",
                            IsEnabled = true,
                            Label = "Hybrid",
                            SortOrder = 2,
                            Value = "hybrid"
                        },
                        new
                        {
                            LookupOptionId = 3,
                            Category = "WorkArrangement",
                            GroupLabel = "Arrangement",
                            IsEnabled = true,
                            Label = "Remote — within region",
                            SortOrder = 3,
                            Value = "remote-regional"
                        },
                        new
                        {
                            LookupOptionId = 4,
                            Category = "WorkArrangement",
                            GroupLabel = "Arrangement",
                            IsEnabled = true,
                            Label = "Remote — anywhere",
                            SortOrder = 4,
                            Value = "remote-global"
                        },
                        new
                        {
                            LookupOptionId = 11,
                            Category = "SeniorityLevel",
                            IsEnabled = true,
                            Label = "Junior",
                            ShortLabel = "Jr",
                            SortOrder = 1,
                            Value = "junior"
                        },
                        new
                        {
                            LookupOptionId = 12,
                            Category = "SeniorityLevel",
                            IsEnabled = true,
                            Label = "Mid",
                            ShortLabel = "Mid",
                            SortOrder = 2,
                            Value = "mid"
                        },
                        new
                        {
                            LookupOptionId = 13,
                            Category = "SeniorityLevel",
                            IsEnabled = true,
                            Label = "Senior",
                            ShortLabel = "Snr",
                            SortOrder = 3,
                            Value = "senior"
                        },
                        new
                        {
                            LookupOptionId = 14,
                            Category = "SeniorityLevel",
                            IsEnabled = true,
                            Label = "Lead",
                            ShortLabel = "Lead",
                            SortOrder = 4,
                            Value = "lead"
                        },
                        new
                        {
                            LookupOptionId = 21,
                            Category = "InterviewType",
                            IsEnabled = true,
                            Label = "Behavioral",
                            SortOrder = 1,
                            Value = "behavioral"
                        },
                        new
                        {
                            LookupOptionId = 22,
                            Category = "InterviewType",
                            IsEnabled = true,
                            Label = "Technical",
                            SortOrder = 2,
                            Value = "technical"
                        },
                        new
                        {
                            LookupOptionId = 23,
                            Category = "InterviewType",
                            IsEnabled = true,
                            Label = "Culture add",
                            SortOrder = 3,
                            Value = "culture"
                        });
                });

            modelBuilder.Entity("HrDraft.Model.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TeamId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.Tool", b =>
                {
                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("EstimatedSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SkillFileNames")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ToolKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ToolId");

                    b.HasIndex("ToolKey")
                        .IsUnique();

                    b.ToTable("Tools", (string)null);

                    b.HasData(
                        new
                        {
                            ToolId = 1,
                            Category = "Recruiting",
                            Description = "Title, seniority, must-haves → full JD with comp and inclusive closing.",
                            DisplayName = "Job description",
                            DisplayNumber = "01",
                            EstimatedSeconds = 20,
                            IsActive = true,
                            MaxOutputTokens = 4000,
                            RequiresHumanReview = true,
                            ShortDescription = "Title, seniority, must-haves → full JD.",
                            SkillFileNames = "hr-job-description/SKILL.md",
                            SortOrder = 1,
                            ToolKey = "job-description"
                        },
                        new
                        {
                            ToolId = 2,
                            Category = "Recruiting",
                            Description = "Paste an old posting → debiased, restructured, inclusive.",
                            DisplayName = "JD rewriter",
                            DisplayNumber = "02",
                            EstimatedSeconds = 25,
                            IsActive = true,
                            MaxOutputTokens = 4000,
                            RequiresHumanReview = true,
                            ShortDescription = "Paste an old posting → debiased.",
                            SkillFileNames = "hr-job-description/SKILL.md",
                            SortOrder = 2,
                            ToolKey = "jd-rewriter"
                        },
                        new
                        {
                            ToolId = 3,
                            Category = "Recruiting",
                            Description = "Competency set by interview type, with follow-ups.",
                            DisplayName = "Interview questions",
                            DisplayNumber = "03",
                            EstimatedSeconds = 20,
                            IsActive = true,
                            MaxOutputTokens = 3000,
                            RequiresHumanReview = false,
                            ShortDescription = "Competency set with follow-ups.",
                            SkillFileNames = "hr-interviewing/SKILL.md;hr-recruiting/prompts/writing-competency-based-interview-questions.md",
                            SortOrder = 3,
                            ToolKey = "interview-questions"
                        },
                        new
                        {
                            ToolId = 4,
                            Category = "Recruiting",
                            Description = "Rating grid with strong / weak answer guidance.",
                            DisplayName = "Scorecard",
                            DisplayNumber = "04",
                            EstimatedSeconds = 18,
                            IsActive = true,
                            MaxOutputTokens = 3000,
                            RequiresHumanReview = false,
                            ShortDescription = "Rating grid with answer guidance.",
                            SkillFileNames = "hr-interviewing/SKILL.md",
                            SortOrder = 4,
                            ToolKey = "scorecard"
                        },
                        new
                        {
                            ToolId = 5,
                            Category = "Onboarding",
                            Description = "Phased milestones by role, manager and goals.",
                            DisplayName = "30/60/90 plan",
                            DisplayNumber = "05",
                            EstimatedSeconds = 25,
                            IsActive = true,
                            MaxOutputTokens = 4000,
                            RequiresHumanReview = false,
                            ShortDescription = "Phased milestones by role and goals.",
                            SkillFileNames = "hr-onboarding/SKILL.md;hr-onboarding/examples/create-30-60-90-day-onboarding-plan.md",
                            SortOrder = 5,
                            ToolKey = "plan-30-60-90"
                        },
                        new
                        {
                            ToolId = 6,
                            Category = "Onboarding",
                            Description = "Week-by-week, systems and equipment included.",
                            DisplayName = "Onboarding checklist",
                            DisplayNumber = "06",
                            EstimatedSeconds = 20,
                            IsActive = true,
                            MaxOutputTokens = 3000,
                            RequiresHumanReview = false,
                            ShortDescription = "Week-by-week, systems included.",
                            SkillFileNames = "hr-onboarding/SKILL.md;hr-onboarding/prompts/employee-onboarding.md",
                            SortOrder = 6,
                            ToolKey = "onboarding-checklist"
                        },
                        new
                        {
                            ToolId = 7,
                            Category = "Onboarding",
                            Description = "First-day message for the team and the new hire.",
                            DisplayName = "Welcome email",
                            DisplayNumber = "07",
                            EstimatedSeconds = 12,
                            IsActive = true,
                            MaxOutputTokens = 1500,
                            RequiresHumanReview = false,
                            ShortDescription = "First-day message for the new hire.",
                            SkillFileNames = "hr-onboarding/SKILL.md",
                            SortOrder = 7,
                            ToolKey = "welcome-email"
                        });
                });

            modelBuilder.Entity("HrDraft.Model.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte>("AuthSource")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DailyGenerationLimit")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasFilter("[EntraObjectId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HrDraft.Model.Entities.AuditEntry", b =>
                {
                    b.HasOne("HrDraft.Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.CompBand", b =>
                {
                    b.HasOne("HrDraft.Model.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany("CompBands")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.CompanyProfile", b =>
                {
                    b.HasOne("HrDraft.Model.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.EmailMessage", b =>
                {
                    b.HasOne("HrDraft.Model.Entities.Generation", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HrDraft.Model.Entities.User", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("SentByUser");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.Generation", b =>
                {
                    b.HasOne("HrDraft.Model.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany()
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrDraft.Model.Entities.Generation", "ParentGeneration")
                        .WithMany()
                        .HasForeignKey("ParentGenerationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HrDraft.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HrDraft.Model.Entities.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrDraft.Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");

                    b.Navigation("ParentGeneration");

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.GenerationRevision", b =>
                {
                    b.HasOne("HrDraft.Model.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HrDraft.Model.Entities.Generation", "Generation")
                        .WithMany("Revisions")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.CompanyProfile", b =>
                {
                    b.Navigation("CompBands");
                });

            modelBuilder.Entity("HrDraft.Model.Entities.Generation", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
